# Generated by Django 3.2.18 on 2024-10-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.IntegerField(verbose_name='Guild ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category_id', models.IntegerField(verbose_name='Category ID')),
                ('role_id', models.IntegerField(null=True, verbose_name='Role ID')),
                ('url', models.SlugField(max_length=255, null=True, verbose_name='URL')),
                ('username', models.SlugField(max_length=255, null=True, verbose_name='Username')),
                ('password', models.SlugField(max_length=255, null=True, verbose_name='Password')),
                ('folder', models.SlugField(max_length=511, verbose_name='Folder Link')),
                ('nexus', models.SlugField(max_length=511, verbose_name='Nexus Link')),
                ('team_name', models.CharField(max_length=255, null=True, verbose_name='Team Name')),
                ('is_bighunt', models.BooleanField(verbose_name='Is Bighunt?')),
                ('logfeed', models.IntegerField(null=True, verbose_name='Logfeed Channel ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='hunt',
            constraint=models.UniqueConstraint(fields=('guild_id', 'category_id'), name='unique_guild_name_combination'),
        ),
    ]
