# Generated by Django 3.2.18 on 2024-10-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunts', '0003_auto_20241009_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='web_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='puzzle',
            constraint=models.UniqueConstraint(fields=('hunt', 'channel_id'), name='unique_hunt_channel_combination'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('hunt', 'category_id'), name='unique_hunt_category_combination'),
        ),
    ]
