# Generated by Django 3.2.18 on 2024-10-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_auto_20241009_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='metas',
            new_name='feeders',
        ),
    ]
