# Generated by Django 3.2.18 on 2024-10-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_rename_metas_puzzle_feeders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='feeders',
            field=models.ManyToManyField(related_name='feeding', to='hunts.Puzzle'),
        ),
    ]
