# Generated by Django 3.2.18 on 2025-10-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0006_alter_puzzle_feeders'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='update_flag',
            field=models.BooleanField(default=False, verbose_name='Update Flag'),
        ),
        migrations.AddField(
            model_name='round',
            name='update_flag',
            field=models.BooleanField(default=False, verbose_name='Update Flag'),
        ),
    ]
