# Generated by Django 3.2.18 on 2025-10-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0007_auto_20251001_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tag Name')),
                ('marker', models.CharField(max_length=7, verbose_name='Marker')),
                ('role', models.CharField(max_length=255, verbose_name='Role To Alert')),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.puzzle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.tag')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='tags',
            field=models.ManyToManyField(related_name='tagged_puzzles', through='hunts.PuzzleTag', to='hunts.Tag'),
        ),
        migrations.AddConstraint(
            model_name='puzzletag',
            constraint=models.UniqueConstraint(fields=('puzzle', 'tag'), name='uniq_puzzle_tag'),
        ),
    ]
