# Generated by Django 3.2.18 on 2026-01-29 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0008_auto_20251025_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='rounds',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hunts.round'),
            preserve_default=False,
        ),
    ]
